# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bun" # bun
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
      
    target-branch: "dependabot-bun"
    commit-message:
      prefix: "[Dependency-bun]: "
    labels:
      - "bun"
      - "dependabot"
      - "dependencies"

  - package-ecosystem: "npm" # npm
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
      
    commit-message:
      prefix: "[Dependency-npm]: "
    target-branch: "dependabot-npm"
    labels:
      - "npm"
      - "dependabot"
      - "dependencies"