name: Combine Dependbot PRs

on:
  schedule:
    - cron: '0 4 * * 7' # Sunday at 04:00
  workflow_dispatch: # allows you to manually trigger the workflow

# The minimum permissions required to run this Action
permissions:
  contents: write # to create a new branch and merge other branches together
  pull-requests: write # to create a new PR with the combined changes
  checks: read # to check if CI is passing or not before combining PRs

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.2.0 # where X.X.X is the latest version
        with:
            select_label: "dependabot"
            labels: "combined-pr" # Optional: add a label to the combined PR